### ISSUE TITLE
password arg 

### ISSUE THREAD

**Issue by kpham123** [Battleman/zoomdl#13]
**Describe the bug**
The code on win10 or Debian enters password arg section and creates this bug, even though no password arg was given. 

Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 57, in <module>
  File "zoom_dl\zoomdl.py", line 33, in zoomdl
UnboundLocalError: local variable 'meet_id' referenced before assignment
[14428] Failed to execute script __main__

**Versions (please complete the following information):**
 - OS: Win10 Enterprise
 - Python Version: 3.7.7
 - ZoomDL Version: 2020.06.17
![Annotation 2020-06-21 210758](https://user-images.githubusercontent.com/8692093/85247656-53ad7680-b403-11ea-949d-440e12000cfc.png)

**Comment by kpham123** [comment]
Confirming the issue is not reproduced in 2020.06.09 version.

**Comment by Battleman** [comment]
Thanks for the feedback. Indeed, I modified the way the main function interacts with the arguments, and misunderstood how it works. Fix should be easy. 

In parallel, I'm in the process of creating a test suite, but it takes time. This kind of problem should be limited in the future, with a decent suite.

**Comment by Battleman** [comment]
This should be fixed in 2020.06.22. Closing now, please reopen if still not fixed.
