### ISSUE TITLE
Meeting Registration Details

### ISSUE THREAD

**Issue by adamtoh97** [Battleman/zoomdl#15]
Hi, 
the zoom recording that I try to download has a meeting registration details and a captcha so perhaps when retrieving it failed in the process. Below is the error message.

Error Code:
  File "zoomdl\__main__.py", line 57, in <module>
  File "zoomdl\zoom_dl\zoomdl.py", line 34, in zoomdl
UnboundLocalError: local variable 'meet_id' referenced before assignment

**Comment by Battleman** [comment]
The registration and CAPTCHA is a known bug, but I lack a recording to test a fix. If you could provide one, I can have a look at it.
Also, obviously, this script is unable to fill in CAPTCHA. So the script would either need to fail gracefully, or ask the user to fill it first (but I must admit I have no idea how this would be implemented...).

**Comment by Battleman** [comment]
Inactive for too long, closing
