### ISSUE TITLE
Change Resolution and Display Progress Bar?

### ISSUE THREAD

**Issue by itisyeetimetoday** [Battleman/zoomdl#18]
**Prerequisite** Tick (`[ ] --> [x]`) if you have done the following:
- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened issues for a duplicate,

**Describe the bug**
This isn't a bug, but I would like to suggest 2 features. First, I would like to suggest the ability to change the output resolution. This would help with reducing the file sizes. Second, I would like to suggest the program to display a progress bar when downloading. This way, it is easier to tell if the user accidentally paused the terminal, and to determine if the program has crashed.

Thank you for your great program, and keep up the good work.

**Comment by Battleman** [comment]
Thanks for your feedback, and sorry for the delay, exams at my uni just finished.

I like your features ideas. Though, the first one probably won't be implemented (at least for now). This requires to interact with ffmpeg, avconv or Open-CV. This seems out of scope for this project, user can convert the video after download. If a PR comes with it, I'll definitely consider it, but I won't get into that for now.

The second one is really cool. I implemented it, and will come in the next version (probably 2020.09.08, that should come out today with a bunch of features/fixes)

**Comment by Battleman** [comment]
Progress bar has been fixed in 2020.09.08. Resolution change won't be implemented for now.
