### ISSUE TITLE
[8612] Failed to execute script __main__

### ISSUE THREAD

**Issue by itisyeetimetoday** [Battleman/zoomdl#21]
**Prerequisite** Tick (`[ ] --> [x]`) if you have done the following:
- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened issues for a duplicate,
I'm on windows 10. I'm still been downloading new recordings from my course, and it no password has been added, however now, i get an error when I try to download the recordings. 
`No video URL in meta, going bruteforce
Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 20, in <module>
  File "zoom_dl\__init__.py", line 18, in main
  File "zoom_dl\zoomdl.py", line 142, in download
  File "zoom_dl\zoomdl.py", line 80, in get_page_meta
AttributeError: 'NoneType' object has no attribute 'group'
[15512] Failed to execute script __main__`

 Previously, after going brute force, it would automatically start downloading.  But now, it won't start downloading. I've tried older releases, but they now have this new issue.

**Comment by Gh0stByte** [comment]
Has your course required you to login now in order to view the lectures?

**Comment by itisyeetimetoday** [comment]
No, I could copy and paste the link and watch the lecture without any password or prompt to end a password.

**Comment by Battleman** [comment]
If the problems appeared for older versions, it may be something changed by Zoom. Would you accept to share the URL ? Either here or in PM on [reddit](https://reddit.com/u/gsbattleman). Otherwise I can't reproduce the bug with the testing URLs I have at hand.

**Comment by itisyeetimetoday** [comment]
I believe it works now. It may have been a glitch, or a temporary error. Thank you for your help.
