### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="? error on /textui/prompt.py:68: 

### ISSUE THREAD

**Issue by morreau** [Battleman/zoomdl#28]
## PLEASE FILL IN THE TEMPLATE BELOW, DON'T SIMPLY ERASE EVERYTHING. ISSUES NOT FOLLOWING THIS TEMPLATE WILL NOT BE CONSIDERED.
**Prerequisite** Tick (`[ ] --> [x]`) if you have done the following:
- [ ] I have updated to the latest version,
- [ ] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [ ] I have searched the opened issues for a duplicate,

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please add below the output of the command you launched, with the `-v 0` flag.
Remember to edit out the password if it is confidential!

```
<LOGS>
```
**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python Version: [e.g. 3.8.7]

**Additional context**
``

**Comment by zmilonas** [comment]
Also running into this warning.

The program behaves like it should. But the warning is printed.
I'm running on macOS Catalina.

This seems to be a problem with the dependency `clint` - here's the supposed line that is refrenced https://github.com/kennethreitz-archive/clint/blob/9d3693d644b8587d985972b6075d970096f6439e/clint/textui/prompt.py#L69

**Comment by Battleman** [comment]
Didn't realize clint was so old. I'm switching to tqdm, which is hopefully better maintained.
