### ISSUE TITLE
Add filename check

### ISSUE THREAD

**Issue by Battleman** [Battleman/zoomdl#3]
Check that the a file with the same name doesn't exist yet, and if it does, ask for confirmation to overwrite

**Comment by skyler14** [comment]
Somewhere right around like 40 to 45 you can do such a check with:

os.path.isfile(filepath)

**Comment by Battleman** [comment]
Fixed in 050993d4def7a08732c566d7796785ae13949d6e. Thanks for the input!
Closing now.
