### ISSUE TITLE
Some characters are not recognized as a password in windows.

### ISSUE THREAD

**Issue by csm-kr** [Battleman/zoomdl#34]
Hi~ 

I am grateful for the usefulness of your zoomdl. 
I think the character "^" is doesn't recognized as a password in windows.
When I tried to download a video with the "^" character in the password, it did not download in the window.
When I debugged using the -v 0 option, the ^ character was gone.

For example:

If I wanted to download videos at the URL with a password containing "^", I type as follows.
zoomdl.exe -u [my URL] -p sEr^e#+

If we set the password is sEr^e#+
I got this error as follows,

...
Checking CAPTCHA
Using password'sEre#+'
...

So I used double quotes at the password,

zoomdl.exe -u [my URL] -p "sEr^e#+"

...
Checking CAPTCHA
Using password'sEr^e#+'
...

It still came out like this, but the password was not resolved.
But on ubuntu, there was no problem at all.

Ask about this issue to make your repository better.
Thank you.

**Comment by Battleman** [comment]
Hi. Have you tried single and double quotes, as explained in the [README](https://github.com/Battleman/zoomdl/blob/master/README.md#about-quotes-important) ?

**Comment by csm-kr** [comment]
Yeah I used a double quote on the window as explained in the README, but nevertheless, it showed a phenomenon that certain characters(^) were not recognized.

**Comment by Battleman** [comment]
Works fine on my test Windows... If it prints what password is used, this string should be strictly used. So the character will be considered. I'm suspecting something else. I'm gonna ask you to re-open an issue with the provided bug template, __without erasing it__. By filling the template, you provide crucial information for me to debug that. If you need to privately send me a url/password to debug, you can do so at zoomdl[at]cloux.dev . Thank you
