### ISSUE TITLE
file size 0 windows 10

### ISSUE THREAD

**Issue by BassemMounir** [Battleman/zoomdl#36]
when the file name has ':' character
it saves empty file with the name cut down to the characters before ':'
example: if the file name is "subject:lecture.mp4"
it saves an empty file with the name "subject"
this only happens on windows. tried it on arch linux.. works fine
tried it with single and double qoutations.. still the same issue
the only solution for this right now is to use -f option
with name without ':' character

**Comment by Battleman** [comment]
Thanks for sharing. Please in the future, follow the "bug" template. It does contain a lot of stuff useful for me...

Still, I managed to reproduce the issue. Didn't know the colon was a prohibited character, among others. It will be fixed in the next upstream.
