### ISSUE TITLE
Issue when downloading a 8+ hours long zoom call

### ISSUE THREAD

**Issue by mflipe** [Battleman/zoomdl#37]
**Prerequisite**

- [X] I have updated to the latest version,
- [X] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**
When I try to download a zoom call of 08:46:48 (almost 9 hours) but the server kicks me out.
I managed to download 1.556.480 KB (1,5 GB) of it but can't download the last 20~40 minutes.
It never stops at the same spot.
The progress bar just stops and after a 5 to 10 minutes (or more) it show that the connection was refused/revoked by the server.

**To Reproduce**
Try to download a 8 to 9 hours zoom call

**Expected behavior**
Download the zoom call

**Versions (please complete the following information):**
 - OS: Windows 10 PRO - 20H2
 - Python Version: 3.9.1

**Suggestion**
Add a way to download a video from point A to point B:
For example if a zoom call has 1500 points (as shown in progress bar), add a command to download from 0 to 500, them 501 to 1000 and 1001 to 1500.  This way you can get the whole video in 3 separated downloads in a way that the server will not revoke the connection.

**Comment by Battleman** [comment]
Well, a strange bug for sure. Never encountered such a long zoom call! Would you be kind enough to send me the link at zoomdl[at]cloux.dev ? I can use it to test some possibilities.

**Comment by mflipe** [comment]
Sure, but I don't know how to sent it to "zoomdl[at]cloux.dev"

**Comment by Battleman** [comment]
replace "at" by "@", and use your preferred email provider

**Comment by mflipe** [comment]
Sorry, I can't share it. copyright protection.

**Comment by Battleman** [comment]
I've added the possibility to resume download. Long story short: when downloading the file, it will be `<filename>.mp4.part` while being downloaded, and will change to `<filename>.mp4` when finished.
When downloading, zoomdl will look for the .part file and resume from there. This is  bit experimental, thus I'm not pushing to master yet (it's available on [resume-dl](https://github.com/Battleman/zoomdl/tree/resume-dl)) . @mflipe if you have a *NIX computer (Linux exec is ready), or are willing to compile for Windows yourself (I don't have my VM accessible), you can try and see if that fixes your problem. Let me know.

**Comment by Battleman** [comment]
resume-dl has been merged into branch Beta

**Comment by Battleman** [comment]
Aaan, now merged into master. This should be fixed in 2021.03.27. If this doesn't work, feel free to reopen and let me know.
