### ISSUE TITLE
Are SSO downloads possible?

### ISSUE THREAD

**Issue by StealthBadger747** [Battleman/zoomdl#41]
**Prerequisite**

- [x] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

**Question**
I am wondering if there is the possibility to download lectures that require a SSO login?

**Comment by Wulfheart** [comment]
Second that question.

**Comment by Battleman** [comment]
So, it _should_ be possible, but still in beta. Head over to [2020.02.15_beta](https://github.com/Battleman/zoomdl/releases/tag/2021.02.15_beta), and download the beta version there. 
Then on a browser, login to access your video with SSO. After that, you copy the value of the cookie `_zm_kms`. Finally, launch the zoomdl command as usual, but add `-a 'theCookieYouJustCopied'`.

It's still experimental, so I'd appreciate feedback on that.

**Comment by Shanesan** [comment]
Utilizing Firefox's "Storage Inspector" tools, I don't have the `_zm_kms` cookie, but I do have the following underscore-first cookies: `__zlcmid`, `_zm_cdn_blocked`, `_zm_csp_script_nonce`, `_zm_currency`, `_zm_date_format`, `_zm_lang`, `_zm_launcher`, `_zm_mtk_guid`, `_zm_page_auth`, `_zm_rf_sp`, `_zm_ssid`.

**Comment by pascal-mueller** [comment]
If I download it and unzip it and then run

`./zoomdl -p 'mypw' -i 'ssid cookie' -u myurl` 

I get

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pascal/Downloads/zoomdl-2021.02.15_beta/./zoomdl/__main__.py", line 20, in <module>
  File "/home/pascal/Downloads/zoomdl-2021.02.15_beta/./zoomdl/zoom_dl/__init__.py", line 18, in main
  File "/home/pascal/Downloads/zoomdl-2021.02.15_beta/./zoomdl/zoom_dl/zoomdl.py", line 184, in download
UnboundLocalError: local variable 'meet_id' referenced before assignment

I'm on arch linux and I run python 3.9.2

**Comment by Battleman** [comment]
This should be fixed in 2021.03.27. If this doesn't work, feel free to reopen and let me know.
For login-protected videos, login to the video and export your cookies (as explained in the [readme](https://github.com/Battleman/zoomdl#cookies--sso--captcha--login)
