### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by pascal-mueller** [Battleman/zoomdl#45]
**Prerequisite**

- [x] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

**Question**
So I tried to download a video but it doesn't work. It's passwort protected and sometimes there's a captcha. I use

zoomdl -p 'pw' -u 'https://subdomain.zoom.com/...' but I keep getting
```
Advanced meta failed
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected? 
Unable to find metadata, aborting.
```
- v 0 gives me
```
Using standard Windows UA
Changing page to ...
Checking CAPTCHA
Using password 'pw'
Changing page to ...
Checking CAPTCHA
Advanced meta failed
Metas are {'is_captcha_hide': 'false', 'action': 'viewdetailpage', 'useWhichPasswd': 'meeting', 'sharelevel': 'meeting', 'meetId': 'GYhvnHeoh6_jh9cIYphBSxB0r9FN6x3khuQyOO6czHbImlX-v8_GI13pX2bTE1wV.Ini1WIpA2yJ_pS0a', 'cookie_currency': 'USD', '__platformCheck': '', 'detect': 'https://st2.zoom.us/cdn-detect.png'}
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected? 
Unable to find metadata, aborting.
```

What's going on? Usually it worked fine.

**Comment by Battleman** [comment]
Hi! Hard to tell without the video. Would you be willing to share the credentials to the video? You can send them by email to zoomdl[at]cloux.dev so only I get them. I can provide a public key if you need encryption.

Also, sometimes this weekend I'm pushing a new version with improved support to cookies, which should help bypass captcha, SSO and others.

**Comment by Battleman** [comment]
I pushed the new version (2021.03.27) yesterday. You can download it, and try the new `--cookies` option. Look at the README for how to use it.
