### ISSUE TITLE
New releases have low download speed and almost full CPU usage

### ISSUE THREAD

**Issue by jasonxytan** [Battleman/zoomdl#49]
**Prerequisite**

- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

For the latest two releases last month, the download speed of videos is much lower than previous releases on same video links and CPU usage gets close to 100%. I've tested on several zoom video links.

[Release v2021.01.01](https://github.com/Battleman/zoomdl/tree/v2021.01.01) worked just fine on those links. I can download at full speed. The CPU usage of Python is low.

[Release v2021.03.27](https://github.com/Battleman/zoomdl/tree/v2021.03.27) and [Release v2021.03.28](https://github.com/Battleman/zoomdl/tree/v2021.03.28) will have the problem stated above. The download speed is always lower than 100 kit/s. And the Python process has nearly 100% CPU usage.

**To Reproduce**

**Expected behavior**

Normal download speed & normal CPU usage

**Screenshots**

v2021.01.01
<img width="1440" alt="v2021 01 01" src="https://user-images.githubusercontent.com/55012776/113479657-e87cee80-94c2-11eb-85a9-77f28365d4e8.png">

v2021.03.28
<img width="1440" alt="v2021 03 28" src="https://user-images.githubusercontent.com/55012776/113479661-ec107580-94c2-11eb-9217-80d1ad68b9c8.png">
<img width="555" alt="v2021 03 28-%CPU" src="https://user-images.githubusercontent.com/55012776/113479662-ef0b6600-94c2-11eb-8eed-d0c74b3076d4.png">

**URL (opt)**

https://...

**Logs**

<v2021.01.01>
```
<LOGS>
Changing page to https://***.zoom.us/rec/share/***
Checking CAPTCHA
Using password '***'
Changing page to https://***.zoom.us/rec/share/***
Checking CAPTCHA
Advanced meta failed
Metas are {'r_is_video': 'true', 'r_meeting_topic': "***'s Personal Meeting Room", 'r_meeting_start_time': 'Mar 21, 2021 10:08 PM Pacific Time (US and Canada)', 'recording_id': '***', 'contiuneMode': '1', 'totalClips': '1', 'currentClip': '1', 'previousClipStartTime': '-1', 'nextClipStartTime': '-1', 'hasPermissionEdit': '0', 'r_offset_start': '0', 'r_offset_end': '0', 'r_duration': '4945', '__platformCheck': 'os', 'detect': 'https://st2.zoom.us/cdn-detect.png'}
No video URL in meta, going bruteforce
Found name is ***'s_Personal_Meeting_Room-Mar 21, 2021 10:08 PM Pacific Time (US and Canada), extension is mp4
Full filepath is ***/***'s_Personal_Meeting_Room-Mar 21, 2021 10_08 PM Pacific Time (US and Canada).mp4
Downloading '***'s_Personal_Meeting_Room-Mar 21, 2021 10_08 PM Pacific Time (US and Canada).mp4'...
```

<v2021.03.28>
```
<LOGS>
Changing page to https://***.zoom.us/rec/share/***
Checking CAPTCHA
Using password '***'
['<input', 'type="password"', 'autocomplete="new-password"', 'id="password"', 'name="password"', 'class="form-control"', 'maxlength="64"', 'placeholder="Passcode"', '/']
['<input', 'type="hidden"', 'id="is_captcha_hide"', 'value="false"', '/']
['<input', 'type="hidden"', 'id="action"', 'value="viewdetailpage"', '/']
['<input', 'type="hidden"', 'id="useWhichPasswd"', 'value="meeting"', '/']
['<input', 'type="hidden"', 'id="sharelevel"', 'value="meeting"', '/']
['<input', 'type="hidden"', 'id="meetId"', 'value="ewRd74lUqIGaCBFy6zWqvkLXH7bt5EdwjEdLHpyRSnow5X43izfyCWO5BxMCRaEj.BdSeQor95NJBBKmq"', '/']
Changing page to https://***.zoom.us/rec/share/***
Checking CAPTCHA
Advanced meta failed
Metas are {'r_is_video': 'true', 'r_meeting_topic': "***'s Personal Meeting Room", 'r_meeting_start_time': 'Mar 21, 2021 10:08 PM Pacific Time (US and Canada)', 'recording_id': '***', 'contiuneMode': '1', 'totalClips': '1', 'currentClip': '1', 'previousClipStartTime': '-1', 'nextClipStartTime': '-1', 'hasPermissionEdit': '0', 'r_offset_start': '0', 'r_offset_end': '0', 'r_duration': '4945', '__platformCheck': 'os', 'detect': 'https://st2.zoom.us/cdn-detect.png'}
No video URL in meta, going bruteforce
Found name is ***'s_Personal_Meeting_Room-Mar 21, 2021 10:08 PM Pacific Time (US and Canada), extension is mp4
Full filepath is ***/***'s_Personal_Meeting_Room-Mar 21, 2021 10_08 PM Pacific Time (US and Canada).mp4, temporary is ***/***'s_Personal_Meeting_Room-Mar 21, 2021 10_08 PM Pacific Time (US and Canada).mp4.part
Downloading '***'s_Personal_Meeting_Room-Mar 21, 2021 10_08 PM Pacific Time (US and Canada).mp4'...
```

**Versions (please complete the following information):**
 - OS: macOS 11.2.3
 - Python Version: 3.9.1

**Additional context (opt)**

**Comment by Battleman** [comment]
Interesting. I've noticed slow speeds, but I had bad internet at the time, so I just thought this was the problem. Thanks for confirming the previous versions don't have that problem, it means I must have changed something that runs too much, and downloads wait on that. Or some 3rd party library. I'll have a look at that (as well as trying to modify the download speed indicator, I'm not satisfied with `kit/s`, means nothing).

**Comment by Battleman** [comment]
Think I've found it. I merged #46 in the lastest versions. This PR introduced the possibility to resume a download. But doing so, I modified the way I call tqdm (for the download bar). In particular, I iterated per byte instead of kilobytes, so each byte was written one at a time. Talk of inefficiency!

I pushed a new version on [Beta](https://github.com/Battleman/zoomdl/blob/Beta/zoomdl). Could you try it? I don't have my Windows VM at hand, so only the *NIX executable is available. Should be OK, I see you have zsh.

**Comment by jasonxytan** [comment]
Thank you! The beta version works for me. (Yet the download speed is not very stable. Maybe it's my local network issue.)

**Comment by jfuzaroa** [comment]
Same here, download speed on beta is fast (and consistent) again. Thanks!

**Comment by Battleman** [comment]
OK great. I'll keep that open until I can compile and merge (I don't have my windows VM now). Probably some time next week. About stability: it may be fixable on my side. I think I use very few samples to determine the speed, so it obviously will vary a lot. I may increase the number of samples, which will reflect a more stable output.

**Comment by dmelendezmaita** [comment]
Fixed: https://github.com/dmelendezmaita/zoomdl/tree/patch-1

**Comment by jenspots** [comment]
I can confirm that using the `Beta` branch restored full download speed for me (on macOS). Thank you!
