### ISSUE TITLE
Picky about Zoom record URL?

### ISSUE THREAD

**Issue by ali-ramadhan** [Battleman/zoomdl#5]
Nice tool @Battleman, thank you for developing this!

Not sure if the README is wrong in saying

> You just need to provide a zoom record URL (starting with zoom.us/rec/play/...)

as it seems I need to provide a URL starting with something like `us02web.zoom.us/rec/play/...`.

```
> python zoomdl.py -u https://zoom.us/rec/play/...

Traceback (most recent call last):
  File "zoomdl.py", line 75, in <module>
    main(args.url, args.filename, args.password)
  File "zoomdl.py", line 15, in main
    domain = domain_re.match(url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

```
> python zoomdl.py -u https://us02web.zoom.us/rec/play/...

Downloading...
Done!
```

**Comment by Battleman** [comment]
Indeed, is supposes a "domain" XXX.zoom.us, as there are other used URLs that need the same domain. I'll change the README for that.
But if you have a valid url that doesn't have a domain (starts only with https://zoom.us/..), please post it here or send it in PM. I've never encountered such urls, i'd be glad to adapt the script for them.

**Comment by Battleman** [comment]
bbea1c1 changes the regexp for valid urls, and updates the README accordingly. I'm closing this now, if it's still a problem you can reopen it.
Cheers
