### ISSUE TITLE
Download all files

### ISSUE THREAD

**Issue by hardianlawi** [Battleman/zoomdl#51]
**Prerequisite**

- [x] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

**Question**

Is it possible to download all the files associated with the recording? Sometimes there are chat messages or transcripts that come with the video.

**Comment by Battleman** [comment]
Hmm, I have to look into that. I guess it's possible, but I don't know how they are stored. If it's a simple file (like txt file) to download it's easy, if they are emulated by javascript or some dynamic component, it's gonna be harder. A test recording with either would help.

**Comment by hardianlawi** [comment]
@Battleman I created [this test recording](https://gojek.zoom.us/rec/share/qDrr1hLXCP9fFl0x92quI3Flh3hsWMJrwxRzAAH-LyXFV-Ulw6A9XKK0KAcu-332.ovYMEu-HhHEWtfSt) previously. I set the expiry date to 30 days. Hope that helps

**Comment by Battleman** [comment]
So this recording has the video, but I see no additional file on the page. When I click to download, it returns the video file as well as a sound-only track of the recording. 
The files are not present on the page; I need to send a POST request to the server, that will return a JSON object containing all the files to download.
I have to check, but I guess the POST will only work if the "download" button is available, on which case the utility of ZoomDL is limited (except for scripting maybe?). Also I'm not sure if it works for other things like subtitles or transcript. If it's only an audio track, it might be easier to call ffmpeg (like youtube-dl) as a post-processor to extract the sound.
Would you be able to produce a recording with some textual data?

**Comment by hardianlawi** [comment]
Hi, thank you for your time. I have found another solution to my problem. I will close this issue for now. Others that feel the need for this could reopen this issue in the future. 🙏
