### ISSUE TITLE
buggy passwords

### ISSUE THREAD

**Issue by ng572** [Battleman/zoomdl#54]
**Prerequisite**

- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

50% +/- 10% of the time I failed to download video because there's something wrong with the password.

OK Examples | Buggy Examples
------------ | -------------
Un=t3+Hu | E$H&X9ZQ
#*7#*gv# | h@2^#mfC
D+ZArGY0 | %nOzW4a2
##UA=4$5 | cs5^h8#8
.?ab0CX7 | H4Zvu%ZR
D8.zs?Yz | @mYzX2^V
y8LZ$zNw | 96P9g%nW

A fair assumption would be that @ ^ & % causes something unexpected.
I have reviewed the https requests and found that the field **passwd** is percent-escaped,
which may or may not have to do with the problem.
```
# reverse engineered python requests code
data = {
    'id': ' irrelevant... ',
    'passwd': 'h@2^#mfC',
    'action': ' irrelevant... ',
    'recaptcha': ' irrelevant... '
}
# original requests code
 --data-raw 'id= irrelevant... &passwd=h%402%5E%23mfC&action= irrelevant... &recaptcha= irrelevant...'
```
I have tried to percent-escape my input to the program but it didn't work.

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - Python Version: [3.9.5]

**Comment by Battleman** [comment]
Hi! Thanks for that. So you mean when you pass the flag `-v 0`, the password that is printed is correct, but it fails nonetheless? I don't know much about windows, but on Linux the way text is treated in the terminal depends on single/double quotes (i.e. double quotes will try to "interpret" special characters, single quotes won't). If the `-v 0` flag displays the correct password, then you may be right and it's a matter of encoding. Never seen that on Linux, maybe Windows is different.

**Comment by ng572** [comment]
> Hi! Thanks for that. So you mean when you pass the flag `-v 0`, the password that is printed is correct, but it fails nonetheless? I don't know much about windows, but on Linux the way text is treated in the terminal depends on single/double quotes (i.e. double quotes will try to "interpret" special characters, single quotes won't). If the `-v 0` flag displays the correct password, then you may be right and it's a matter of encoding. Never seen that on Linux, maybe Windows is different.

```
> zoomdl -v 0 -u irrelevant... -p E$H&X9ZQ

Changing page to irrelevant...
Checking CAPTCHA
Using password 'E$H'
```
```
> zoomdl -v 0 -u irrelevant... -p "E$H&X9ZQ"

Changing page to irrelevant...
Checking CAPTCHA
Using password 'E$H&X9ZQ'
```
in both cases, the program eventually failed.

**Comment by Battleman** [comment]
Ok, then it may be an encoding issue. Probably not too hard to debug, I'll create a test recording with one of the failing password and have a look when I get a chance.

**Comment by ng572** [comment]
> Ok, then it may be an encoding issue. Probably not too hard to debug, I'll create a test recording with one of the failing password and have a look when I get a chance.

Hi, I just realized I made a mistake. Because I already logged in using the browser, the password argument was extraneous and was causing error..
```
> zoomdl -v 0 -u irrelevant... -p "E$H&X9ZQ"

Changing page to irrelevant...
Checking CAPTCHA
Using password 'E$H&X9ZQ'
```
this console command should have worked otherwise.

Which means this bug report was a false alarm. Sorry!

double-quoting the password should have resolved everything.

I think it may be better if the program try to access the video without password first because many of us may have already logged in with a password

**Comment by Battleman** [comment]
Great to hear it's resolved. But I'm not sure I understand how? Whether you were logged in with your browser shouldn't matter, as ZoomDL won't read your browser's cookies (unless you explicitly provide them).

**Comment by ng572** [comment]
> Great to hear it's resolved. But I'm not sure I understand how? Whether you were logged in with your browser shouldn't matter, as ZoomDL won't read your browser's cookies (unless you explicitly provide them).

yes I was wondering that too, maybe I have given an authentication token (-a) but have forgotten by now.
