### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Ragnar1234567** [Battleman/zoomdl#58]
when i run zoomdl -u  {ULR} -p {password} -v 0 command
this "IndexError: list index out of range" shows and stops

**Comment by Oorha** [comment]
Same! This issue is fixed by rolling back to an older version.

**Comment by Battleman** [comment]
Should be fixed in [Beta](https://github.com/Battleman/zoomdl/tree/Beta). Can you confirm?

**Comment by Oorha** [comment]
Confirmed! Issue resolved, thank you!
