### ISSUE TITLE
Duplicate Segments

### ISSUE THREAD

**Issue by Oorha** [Battleman/zoomdl#59]
**Prerequisite**

- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

When downloading a 3 part zoom session, it will download the first part 3 times. Tinkering with -c for every possible outcome has the same result.

**Expected behavior**

Expecting it to download the 3 individual parts.

**Versions (please complete the following information):**
 - OS: [macOS Big Sur v11.4]
 - Python Version: [3.8.11]

**Comment by Battleman** [comment]
Ah, didn't really think of that when fixing #56. I'll have to look at that too. Would you by any chance have a test recording to provide? You can send it to zoomdl[at]cloux.dev if you prefer. It would make the fix easier to test.

**Comment by Battleman** [comment]
Should be fixed in [Beta](https://github.com/Battleman/zoomdl/tree/Beta). can you confirm?

**Comment by Oorha** [comment]
Hey Battleman, it worked great! Issue resolved, thank you!
