### ISSUE TITLE
Include chat as subtitles of the video

### ISSUE THREAD

**Issue by rdrg109** [Battleman/zoomdl#61]
**Prerequisite**

- [ ] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

This is a feature request.

**Question**

Would it be possible to insert the chat as subtitles of the download video? 

I think #51 is related, but I wonder whether there have been further consideration on this topic.

**Comment by Battleman** [comment]
So, this is probably _technically_ possible. Although I'm wondering two things:
* Is it in scope of this project? It would require to interact with ffmpeg or similar. It's not impossible, but it adds a whole layer of complexity
* Is it worth it? The chat is different from the spoken text and likely will seem out of place. Also, IIRC subtitles have a finite "speed" at which they can be displayed. In case of short bursts of messages, either some messages won't be displayed, or the former ones will quickly be overwritten by one just after.

I see two potential ideas:
* Simply download the text as a secondary file. This should absolutely be possible in principle.
* Try to somehow integrate the text as a "secondary". Like, create a chat-like pseudo-video containing the messages as they appear, and hstack it to the recording with ffmpeg. This sounds terribly out of scope for this project, but I like the challenge so I may (very hypothetical) look at it as a new project (and maybe loosely integrate it here).

**Comment by Battleman** [comment]
This has been added in v2021.12.13
