### ISSUE TITLE
zoomdl.exe Not Working Using cmd in Windows

### ISSUE THREAD

**Issue by Ayush2001-boop** [Battleman/zoomdl#62]
**Prerequisite**

- [x] I am asking a question, and not reporting a bug or a feature request
- [] I have searched the opened and closed issues for a duplicate,

**Question**
I tried to run the zoomdl.exe using cmd from my windows computer. The application opens for like 3 seconds and closes on itself. I have Norton Anti Virus software but it showed no warnings for running this application. So I believe my anti-virus did not close the zoomdl.exe. Then what could be the reason that the application opens for 3 seconds and then closes.

**Comment by Battleman** [comment]
Hi. Zoom_dl is not meant to be executed by double-clicking it. Rather you need to open cmd, navigate to where the script is located, and run using the appropriate arguments. see [this part](https://github.com/Battleman/zoomdl#usage) of the readme.

**Comment by Ayush2001-boop** [comment]
It worked for me but now I am getting index error and it says "list is out or range" and "[21044] Failed to execute script __main"
You can see the screenshot here. 
![error](https://user-images.githubusercontent.com/85201352/127039448-b88ea61c-9add-47cc-8443-85009ed7e881.png)

**Comment by jacobrosenfeld** [comment]
I actually made it universally available on my Mac and then just use the directory as the save location.

**Comment by Battleman** [comment]
@Ayush2001-boop can you confirm the executable at [Beta](https://github.com/Battleman/zoomdl/tree/Beta) works?

**Comment by Ayush2001-boop** [comment]
@Battleman I don't know how to downgrade to the previous version! Is Beta the previous version ??

**Comment by Battleman** [comment]
Beta is now the new version. Visit the link above and download `zoomdl.exe`, and use that to replace the executable you're currently using.

**Comment by Ayush2001-boop** [comment]
@Battleman The beta version workd for me. Thank you very much for building such an awesome thing!!
