### ISSUE TITLE
Add FFMPEG support to allow extracting of audio and other video conversions and editing built in

### ISSUE THREAD

**Issue by jacobrosenfeld** [Battleman/zoomdl#68]
**Prerequisite**

- [] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

**Question**
Add FFMPEG support to allow extracting of audio and other video conversions and editing built in

**Comment by Battleman** [comment]
Hi,
Sorry, but I don't think I'll spend time on that. This will add a whole additional level of complexity, IMO out of scope for this project. Making it work with both Windows and Linux will also be a pain. 
If someone is willing to work on a PR I would consider it.
