### ISSUE TITLE
Not functioning on Windows 10

### ISSUE THREAD

**Issue by nihility2018** [Battleman/zoomdl#8]
That said I am new to any kind of coding. I got my python installed and try to use the script but nothing happens. Could you give any suggestion?

**Comment by Battleman** [comment]
Hey. The script was not designed neither tested under Windows (as I don't have any working Windows installation). However, it's possible it works, as there are note many OS-specific features.

Could you elaborate your question ? How are you launching it, what is the console output,... ?

**Comment by Battleman** [comment]
I pushed an executable, `zoomdl.exe`. It should work. Reopen if it doesn't.
